-- ==========================================================================
-- 01_schema.sql
-- spring_db / spring_db_test 스키마 DDL (테이블, 시퀀스 등) - OracleFREE 23c
-- ===========================================================================

CREATE TABLE TBL_BOARD (
    BNO         NUMBER(19)                   GENERATED BY DEFAULT AS IDENTITY,
    TITLE       VARCHAR2(500)                NOT NULL,
    CONTENT     VARCHAR2(2000)               NOT NULL,
    WRITER      VARCHAR2(50)                 NOT NULL,
    REGDATE     TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATEDATE  TIMESTAMP       DEFAULT SYSTIMESTAMP,
    DELFLAG     BOOLEAN         DEFAULT FALSE,
    CONSTRAINT PK_TBL_BOARD PRIMARY KEY (BNO)
);