version: "0.2"
ignorePaths:
  - tomcat-run.bat
  - tomcat-run.sh
  - mvnw.cmd
  - mvnw
dictionaryDefinitions: []
dictionaries: []
words:
  - codehaus
  - deployables
  - fileset
  - filesets
  - mvcpractice
ignoreWords: []
import: []
