version: "0.2"
ignorePaths:
  - tomcat-run.bat
  - tomcat-run.sh
  - mvnw.cmd
  - mvnw
dictionaryDefinitions: []
dictionaries: []
words:
  - codehaus
  - deployables
  - Dmdep
  - Dskip
  - errorlevel
  - fileset
  - filesets
  - FREEPDB
  - gvenzl
  - healthcheck
  - mvcpractice
  - oradata
  - Plinux
  - Premain
  - retransform
  - SETLOCAL
  - SQLCODE
  - SQLERROR
  - sqlplus
  - temurin
  - webapps
  - Xlog
ignoreWords: []
import: []
