version: "0.2"
ignorePaths:
  - tomcat-run.bat
  - tomcat-run.sh
  - mvnw.cmd
  - mvnw
dictionaryDefinitions: []
dictionaries: []
words:
  - aspectj
  - aspectjrt
  - bytebuddy
  - classfile
  - codehaus
  - deployables
  - Dmdep
  - Dskip
  - errorlevel
  - fileset
  - filesets
  - FREEPDB
  - gvenzl
  - healthcheck
  - Hikari
  - hikaricp
  - jquery
  - jsessionid
  - logback
  - mvcpractice
  - ojdbc
  - oradata
  - Plinux
  - Premain
  - projectlombok
  - retransform
  - rttr
  - SETLOCAL
  - SQLCODE
  - SQLERROR
  - sqlplus
  - temurin
  - ultraq
  - webapps
  - webjars
  - webmvc
  - Xlint
  - Xlog
  - Xshare
  - zaxxer
ignoreWords: []
import: []
