#!/bin/sh
# build-scripts/generate-toolchains.ps1의 Linux/macOS 대응 스크립트.
# setenv.properties를 읽어 프로젝트 루트에 toolchains.xml을 생성한다.
set -eu

usage() {
    cat <<'USAGE'
Usage: generate-toolchains.sh [options]

  -p, --properties-path <file>  읽어들일 properties 파일 (기본: <프로젝트 루트>/setenv.properties)
  -o, --output-path <file>      생성할 toolchains.xml 경로 (기본: <프로젝트 루트>/toolchains.xml)
      --print-jdk-home          XML을 만들지 않고, 해석된 JDK 경로만 표준출력으로 내보낸다.
  -h, --help                    이 도움말 출력

JDK 경로는 JAVA_HOME_LINUX -> JAVA_HOME -> 환경변수 JAVA_HOME 순으로 찾는다.
properties 값 앞의 ~ 나 $HOME 은 셸이 확장해주지 않으므로 이 스크립트가 직접 펼친다.
USAGE
}

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROPERTIES_PATH="${SCRIPT_DIR}/../setenv.properties"
OUTPUT_PATH="${SCRIPT_DIR}/../toolchains.xml"
PRINT_JDK_HOME_ONLY=0

while [ $# -gt 0 ]; do
    case "$1" in
        -p|--properties-path)
            [ $# -ge 2 ] || { echo "[ERROR] $1 requires a value." >&2; exit 1; }
            PROPERTIES_PATH="$2"
            shift 2
            ;;
        -o|--output-path)
            [ $# -ge 2 ] || { echo "[ERROR] $1 requires a value." >&2; exit 1; }
            OUTPUT_PATH="$2"
            shift 2
            ;;
        --print-jdk-home)
            PRINT_JDK_HOME_ONLY=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "[ERROR] Unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

if [ ! -f "$PROPERTIES_PATH" ]; then
    echo "[ERROR] Properties file not found: $PROPERTIES_PATH" >&2
    exit 1
fi

# properties에서 키 하나를 읽는다.
# 주석(#, ;)과 빈 줄은 건너뛰고, CRLF의 \r 과 앞뒤 공백은 제거한다. 같은 키는 마지막 값을 쓴다.
read_prop() {
    awk -v key="$1" '
        { sub(/\r$/, "") }
        /^[ \t]*[#;]/ || /^[ \t]*$/ { next }
        {
            sep = index($0, "=")
            if (sep <= 1) next
            k = substr($0, 1, sep - 1); gsub(/^[ \t]+|[ \t]+$/, "", k)
            if (k != key) next
            v = substr($0, sep + 1); gsub(/^[ \t]+|[ \t]+$/, "", v)
            value = v
        }
        END { print value }
    ' "$PROPERTIES_PATH"
}

# 프로퍼티 값의 ~ / $HOME / ${HOME} 접두어를 실제 홈 디렉터리로 펼친다.
expand_home() {
    case "$1" in
        "~")        printf '%s' "$HOME" ;;
        "~/"*)      printf '%s%s' "$HOME" "${1#\~}" ;;
        '$HOME'*)   printf '%s%s' "$HOME" "${1#\$HOME}" ;;
        '${HOME}'*) printf '%s%s' "$HOME" "${1#\$\{HOME\}}" ;;
        *)          printf '%s' "$1" ;;
    esac
}

jdkHome=$(read_prop JAVA_HOME_LINUX)
[ -n "$jdkHome" ] || jdkHome=$(read_prop JAVA_HOME)
[ -n "$jdkHome" ] || jdkHome="${JAVA_HOME:-}"

if [ -z "$jdkHome" ]; then
    echo "[ERROR] JAVA_HOME_LINUX or JAVA_HOME was not found in properties file: $PROPERTIES_PATH" >&2
    exit 1
fi

jdkHome=$(expand_home "$jdkHome")

if [ "$PRINT_JDK_HOME_ONLY" -eq 1 ]; then
    printf '%s\n' "$jdkHome"
    exit 0
fi

# 윈도우용 경로(C:/JDK/21)를 리눅스에서 그대로 쓴 경우를 미리 알려준다.
if [ ! -x "${jdkHome}/bin/javac" ]; then
    echo "[WARN] javac not found under: ${jdkHome}" >&2
    echo "[WARN] setenv.properties의 JAVA_HOME_LINUX 값을 확인하세요." >&2
fi

jdkVersion=$(read_prop JDK_VERSION)
if [ -z "$jdkVersion" ]; then
    echo "[ERROR] JDK_VERSION was not found in properties file: $PROPERTIES_PATH" >&2
    exit 1
fi

jdkVendor=$(read_prop JDK_VENDOR)
if [ -z "$jdkVendor" ]; then
    echo "[ERROR] JDK_VENDOR was not found in properties file: $PROPERTIES_PATH" >&2
    exit 1
fi

xml_escape() {
    printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' \
        -e 's/"/\&quot;/g' -e "s/'/\&apos;/g"
}

cat > "$OUTPUT_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<toolchains>
  <!-- Auto-generated by build-scripts/generate-toolchains.sh -->
  <toolchain>
    <type>jdk</type>
    <provides>
      <version>$(xml_escape "$jdkVersion")</version>
      <vendor>$(xml_escape "$jdkVendor")</vendor>
    </provides>
    <configuration>
      <jdkHome>$(xml_escape "$jdkHome")</jdkHome>
    </configuration>
  </toolchain>
</toolchains>
EOF

echo "[OK] Generated toolchains.xml: $OUTPUT_PATH"
