param(
    [string]$PropertiesPath = (Join-Path $PSScriptRoot "..\setenv.properties"),
  [string]$OutputPath = (Join-Path $PSScriptRoot "..\toolchains.xml")
)

$resolvedPropertiesPath = (Resolve-Path -LiteralPath $PropertiesPath -ErrorAction Stop).Path
$javaHome = $null
$props = @{}

Get-Content -LiteralPath $resolvedPropertiesPath | ForEach-Object {
    $line = $_.Trim()

    if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith("#") -or $line.StartsWith(";")) {
        return
    }

    $separatorIndex = $line.IndexOf("=")
    if ($separatorIndex -le 0) {
        return
    }

    $key = $line.Substring(0, $separatorIndex).Trim()
    $value = $line.Substring($separatorIndex + 1).Trim()
    $props[$key] = $value

    if ($key -eq "JAVA_HOME") {
        $javaHome = $value
    }
}

if ([string]::IsNullOrWhiteSpace($javaHome)) {
  throw "JAVA_HOME was not found in properties file: $resolvedPropertiesPath"
}

$jdkVersionValue = $null
if ($props.ContainsKey("JDK_VERSION") -and -not [string]::IsNullOrWhiteSpace($props["JDK_VERSION"])) {
    $jdkVersionValue = $props["JDK_VERSION"]
}

$vendorValue = $null
if ($props.ContainsKey("JDK_VENDOR") -and -not [string]::IsNullOrWhiteSpace($props["JDK_VENDOR"])) {
    $vendorValue = $props["JDK_VENDOR"]
}

if ([string]::IsNullOrWhiteSpace($jdkVersionValue)) {
  throw "JDK_VERSION was not found in properties file: $resolvedPropertiesPath"
}

if ([string]::IsNullOrWhiteSpace($vendorValue)) {
  throw "JDK_VENDOR was not found in properties file: $resolvedPropertiesPath"
}

$javaHome = $javaHome -replace "\\", "/"
$javaHomeEscaped = [System.Security.SecurityElement]::Escape($javaHome)
$jdkVersionEscaped = [System.Security.SecurityElement]::Escape($jdkVersionValue)
$vendorEscaped = [System.Security.SecurityElement]::Escape($vendorValue)

$toolchainsXml = @"
<?xml version="1.0" encoding="UTF-8"?>
<toolchains>
  <!-- Auto-generated by build-scripts/generate-toolchains.ps1 -->
  <toolchain>
    <type>jdk</type>
    <provides>
      <version>$jdkVersionEscaped</version>
      <vendor>$vendorEscaped</vendor>
    </provides>
    <configuration>
      <jdkHome>$javaHomeEscaped</jdkHome>
    </configuration>
  </toolchain>
</toolchains>
"@

Set-Content -LiteralPath $OutputPath -Value $toolchainsXml -Encoding UTF8
Write-Host "[OK] Generated toolchains.xml: $OutputPath"
